export enum EstadoSolicitud {
	ENVIADA = "ENVIADA",
	APROBADA_SOPORTE = "APROBADA_SOPORTE",
	RECHAZADA_SOPORTE = "RECHAZADA_SOPORTE",
	EN_ANALISIS = "EN_ANALISIS",
	PRESUPUESTADA = "PRESUPUESTADA",
	ACEPTADA = "ACEPTADA",
}
