export * from "./categoria.model";
export * from "./certificadoEstudio.model";
export * from "./comentario.model";
export * from "./direccion.model";
export * from "./localidad.model";
export * from "./profesional.model";
export * from "./provincia.model";
export * from "./solicitudTrabajo.model";
export * from "./usuario.model";
